config/routes.rb
Rails.application.routes.draw do
  resources :images
  resources :maps
  resources :areas
  get 'users/index'

  get 'users/show'

  devise_for :users, :controllers => { :registrations => 'devise/registrations' }
  resources :users, :only => [:index, :show, :destroy]
  root 'home#index'

end

app/models/map.rb
class Map < ActiveRecord::Base
    has_many :images, dependent: :destroy
    accepts_nested_attributes_for :images
    has_many :areas, dependent: :destroy
    accepts_nested_attributes_for :areas
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  # GET /maps
  # GET /maps.json
  def index
    @maps = Map.all
  end

  # GET /maps/1
  # GET /maps/1.json
  def show
    #added this so I can get the image to be used as the map
    @image = @map.images.first
    @images = @map.images.all
    #added this next line - trying to figure it out
    @areas = @map.areas.all
  end

  # GET /maps/new
  def new
    @map = Map.new
    @image = @map.images.build
    @images = @map.images.all
  end

  # GET /maps/1/edit
  def edit
    @image = @map.images.build
    @images = @map.images.all
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(map_params)

    respond_to do |format|
      if @map.save
        if params.has_key?(:images)
           params[:images]['image'].each do |a|
              @image = @map.images.create!(:image => a)
           end
        end
        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render :show, status: :created, location: @map }
      else
        format.html { render :new }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maps/1
  # PATCH/PUT /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        if params.has_key?(:images)
           params[:images]['image'].each do |a|
              @image = @map.images.create!(:image => a)
           end
        end
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { render :show, status: :ok, location: @map }
      else
        format.html { render :edit }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url, notice: 'Map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_params
      params.require(:map).permit(:name, images_attributes: [:id, :map_id, :image, :width, :height])
    end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_form.html.erb
<%= form_for @map, :html => { :class => "form-horizontal map" } do |f| %>

  <% if @map.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@map.errors.count, "error") %> prohibited this map from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @map.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  
  <div class="form-group">  
    <% if @images.exists? %>
      <%= f.label :map_image, :class => 'control-label col-lg-2'  %>
        <div class="col-lg-10">
          <% @images.each do |p| %>
                <div class="form-control">
                  <%= image_tag p.image_url, :class => 'form-control-image' %>

                <%= link_to '<i class="fa fa-edit"></i>'.html_safe,
                      edit_image_path(p), :class => 'form-control-button', 
                      :title => 'Edit Attachment'  %>
                </div>
                
          <% end %>
        </div>
    
    <% else %>  
         <%= f.label :map_image, :class => 'control-label col-lg-2'  %>
         <div class="col-lg-10">
         <%= f.file_field :image, :multiple => true, name: "images[image][]", :class => 'form-control' %>
         </div>
    <% end %>
  </div>  
  
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                maps_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/maps/_newform.html.erb
<%= form_for @map, :html => { :class => "form-horizontal map" } do |f| %>

  <% if @map.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@map.errors.count, "error") %> prohibited this map from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @map.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  
  <div class="form-group">  
    <% if @images.exists? %>
      <%= f.label :map_image, :class => 'control-label col-lg-2'  %>
        <div class="col-lg-10">
          <% @images.each do |p| %>
                <div class="form-control">
                  <%= image_tag p.image_url, :class => 'form-control-image' %>

                <%= link_to '<i class="fa fa-edit"></i>'.html_safe,
                      edit_image_path(p), :class => 'form-control-button', 
                      :title => 'Edit Attachment'  %>
                </div>
                
          <% end %>
        </div>
    
    <% else %>  
         <%= f.label :map_image, :class => 'control-label col-lg-2'  %>
         <div class="col-lg-10">
         <%= f.file_field :image, :multiple => true, name: "images[image][]", :class => 'form-control' %>
         </div>
    <% end %>
  </div>  
  
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                maps_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/maps/edit.html.erb
<%- model_class = Map -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/maps/index.html.erb
<%- model_class = Map -%>

<p>*Maps#index - Here you can add new Maps. Very simple to use. Select the map you want to upload and name it.

<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:map) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @maps.each do |map| %>
      <tr>
        <td><%= link_to map.id, map_path(map) %></td>
        <td>
          <% map.images.each do |p| %>
            <%= link_to image_tag(p.image_url, :style => 'max-width:50px;padding:2px;'), map_path(map) %>
          <% end %>
        </td>
        <td><%= map.name %></td>
        <td><%=l map.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_map_path(map), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      map_path(map),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Image Map =>',
            new_map_path,
            :class => 'btn btn-primary' %>

app/views/maps/new.html.erb
<%- model_class = Map -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'newform' %>

app/views/maps/show.html.erb
<%- model_class = Map -%>

<p>
  *Maps#show - This is an individual Map show page. It acts as an index of the Areas that belong to this Map instance.
  <br><br>
  *Go ahead and add or edit a shape! - Colors change according to status and you can click through into the area!!!
  
</p>

<h1 style="text-align:center;"><%= @map.name %></h1>

<div id='map' style="height:500px;"></div>


<script>
	//A Leaflet map has one CRS (and one CRS only), that can be changed when creating the map. 
	//In a CRS.Simple, one horizontal map unit is mapped to one horizontal pixel, 

	var map = L.map('map', {
		crs: L.CRS.Simple,
		minZoom: -3
	});

	//If working with [y, x] coordinates with something named L.LatLng doesn’t make much sense to you, 
	//you can easily create wrappers for them:
	var yx = L.latLng;

	var xy = function(x, y) {
		if (L.Util.isArray(x)) {    // When doing xy([x, y]);
			return yx(x[1], x[0]);
		}
		return yx(y, x);  // When doing xy(x, y);
	};
	//Now we can add a few stars and even a navigation line with [x, y] coordinates! (Shown down the page a bit)

	//Then we can just add a L.ImageOverlay with the starmap image and its approximate bounds:

	var bounds = [xy(0,0), xy(<%= @image.width %>,<%= @image.height %>)];

	var image = L.imageOverlay('<%= @image.image_url %>', bounds).addTo(map);
	
	//map.setView(xy(120, 70), 1);
    map.fitBounds(bounds);

    var popup = L.popup();
    
	//Let’s define our own icon class containing the shared options, 
    //inheriting from L.Icon! It’s really easy in Leaflet:
    var mapIcon = L.Icon.extend({
			options: {
				shadowUrl: '/images/marker-shadow.png',
				iconSize:     [30, 45], // size of the icon
                shadowSize:   [41, 41], // size of the shadow
                iconAnchor:   [15, 43], // point of the icon which will correspond to marker's location
                shadowAnchor: [12, 38],  // the same for the shadow
                popupAnchor:  [-3, -76] // point from which the popup should open relative to the iconAnchor
			}
		});

    //Now we can create all three of our leaf icons from this class and use them:
    var greenIcon = new mapIcon({iconUrl: '/images/green-marker.png'}),
    redIcon = new mapIcon({iconUrl: '/images/red-marker.png'}),
    orangeIcon = new mapIcon({iconUrl: '/images/orange-marker.png'}),
    blueIcon = new mapIcon({iconUrl: '/images/blue-marker.png'}),
    lblueIcon = new mapIcon({iconUrl: '/images/lblue-marker.png'}),
    blackIcon = new mapIcon({iconUrl: '/images/black-marker.png'}),
    yellowIcon = new mapIcon({iconUrl: '/images/yellow-marker.png'});    
    
    
    <% @areas.each do |area| %>
        var <%= 's' + area.name.gsub(/\W\s?/, "") %> = <%= area.coords.html_safe %>;
        
        L.geoJson(<%= 's' + area.name.gsub(/\W\s?/, "") %>, {
        pointToLayer: function (feature, latlng) {
        return L.marker(latlng, {<% if area.status == 'Available' %>icon: redIcon<% elsif area.status == 'Leased'  %>icon: greenIcon<% else %>icon: lblueIcon <% end %>});
        }}).addTo(map).bindPopup('<h3><%= link_to area.name, area_path(area) %></h3><p><%= area.info %><br><%= link_to "More Info...", area_path(area) %></p>').setStyle(<% if area.status == 'Leased' %>{fillColor: '#00dd00', color: '#00dd00', weight: 1}<% else %>{fillColor: '#dd0000', color: '#dd0000', weight: 1}<% end %>);

    
    <% end %>
</script>



<br style="clear:both;">


<div class="page-header">
  <h1>Areas</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:map_id) %></th>
      <th><%= model_class.human_attribute_name(:info) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <!--<th><%#= model_class.human_attribute_name(:coords) %></th>-->
      <!--<th><%#= model_class.human_attribute_name(:created_at) %></th>-->
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= link_to area.id, area_path(area) %></td>
        <td><%= link_to area.name, area_path(area) %></td>
        <td><%= area.map_id %></td>
        <td style="max-width:40%;"><%= area.info %></td>
        <td><%= area.status %></td>
        <!--<td><%#= area.coords %></td>-->
        <!--<td><%#=l area.created_at %></td>-->
        <td style="min-width:180px;">
          <%= link_to t('.view', :default => t("helpers.links.view")),
                      area_path(area), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_area_path(area), :class => 'btn btn-primary btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      area_path(area),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Area =>',
            new_area_path(:map_id => @map),
            :class => 'btn btn-primary' %>
            
            <br><br><br>
            
            
<hr style="clear:both;">

<div style="width:100%;text-align:center;">
<%= link_to '<= Back to maps',
              maps_path, :class => 'btn btn-default'  %>
<%= link_to 'Edit Map =>',
              edit_map_path(@map), :class => 'btn btn-primary' %>
<%= link_to 'Delete Map X',
              map_path(@map),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>
<hr style="clear:both;">
<br><br>