config/routes.rb
Rails.application.routes.draw do
  resources :images
  resources :maps
  resources :areas
  get 'users/index'

  get 'users/show'

  devise_for :users, :controllers => { :registrations => 'devise/registrations' }
  resources :users, :only => [:index, :show, :destroy]
  root 'home#index'

end

app/models/area.rb
class Area < ActiveRecord::Base
  belongs_to :map
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
    @map = Map.find(@area.map_id)
    #added this so I can get the image to be used as the map
    @image = @map.images.first
    @images = @map.images.all
  end

  # GET /areas/new
  def new
    @area = Area.new
    #testing:
    @map = Map.find(params[:map_id])
    @image = @map.images.first
    @images = @map.images.all
    @areas = @map.areas.all
  end

  # GET /areas/1/edit
  def edit
    @map = Map.find(@area.map_id)
    #added this so I can get the image to be used as the map
    @image = @map.images.first
    @images = @map.images.all
    @areas = @map.areas.all
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)
    @map = Map.find(@area.map_id)

    respond_to do |format|
      if @area.save
        format.html { redirect_to map_url(@map), notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    @map = Map.find(@area.map_id)
    
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to map_url(@map), notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to map_path(@area.map_id), notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:name, :map_id, :info, :status, :coords)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_form.html.erb
<%= form_for @area, :html => { :class => "form-horizontal area" } do |f| %>

  <% if @area.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@area.errors.count, "error") %> prohibited this area from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @area.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  
  <div class="form-group" style="display:none;">
    <%= f.label :map_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-2">
      <%#= f.select :map_id, ['Prospect', 'In Process', 'Complete'], {include_blank:false}, :class => 'form-control' %>
      <%#= collection_select(:area, :map_id, Map.all, :id, :name) %>
      <%= f.text_field :map_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:map_id) %>
  </div>
  
  <div class="form-group">
    <%= f.label :info, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :info, :class => 'form-control' %>
    </div>
    <%=f.error_span(:info) %>
  </div>
  <div class="form-group">
    <%= f.label :status, :class => 'control-label col-lg-2' %>
    <div class="col-lg-2">
      <%= f.select :status, ['Available', 'Leased'], {include_blank:false}, :class => 'form-control' %>
      <%#= f.text_field :status, :class => 'form-control' %>
    </div>
    <%=f.error_span(:status) %>
  </div>
  <div class="form-group">
    <%= f.label :coords, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :coords, :class => 'form-control' %>
    </div>
    <%=f.error_span(:coords) %>
  </div>



  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <p>*Make sure you saved next to the edit icon in the left toolbar if you edited the shape or moved a marker.</p>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                map_path(@map), :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/areas/_newform.html.erb
<%= form_for @area, :html => { :class => "form-horizontal area" } do |f| %>

  <% if @area.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@area.errors.count, "error") %> prohibited this area from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @area.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  
  <div class="form-group" style="display:none;">
    <%= f.label :map_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-2">
      <%#= f.select :map_id, ['Prospect', 'In Process', 'Complete'], {include_blank:false}, :class => 'form-control' %>
      <%#= collection_select(:area, :map_id, Map.all, :id, :name) %>
      <%= f.text_field :map_id, value: params[:map_id], :class => 'form-control' %>
    </div>
    <%=f.error_span(:map_id) %>
  </div>
  
  <div class="form-group">
    <%= f.label :info, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :info, :class => 'form-control' %>
    </div>
    <%=f.error_span(:info) %>
  </div>
  <div class="form-group">
    <%= f.label :status, :class => 'control-label col-lg-2' %>
    <div class="col-lg-2">
      <%= f.select :status, ['Available', 'Leased'], {include_blank:false}, :class => 'form-control' %>
      <%#= f.text_field :status, :class => 'form-control' %>
    </div>
    <%=f.error_span(:status) %>
  </div>
  
  <div class="form-group">
    <%= f.label :coords, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :coords, :class => 'form-control' %>
    </div>
    <%=f.error_span(:coords) %>
  </div>



  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                map_path(@map), :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/areas/edit.html.erb
<%- model_class = Area -%>

<p>
	*Edit Area is simple. Click the edit icon in the left toolbar to change the shape or move a marker.<br><br>
	
	**Click "save" next to the edit icon in the left toolbar and then "Update Area" at the bottom.<br><br>
	
	***The color of the marker does not change until you change the status and save/update.
</p>

<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>

<div id='map' style="height:500px;"></div>


<script>
	//A Leaflet map has one CRS (and one CRS only), that can be changed when creating the map. 
	//In a CRS.Simple, one horizontal map unit is mapped to one horizontal pixel, 

	var map = L.map('map', {
		crs: L.CRS.Simple,
		minZoom: -3
	});

	//If working with [y, x] coordinates with something named L.LatLng doesn’t make much sense to you, 
	//you can easily create wrappers for them:
	var yx = L.latLng;

	var xy = function(x, y) {
		if (L.Util.isArray(x)) {    // When doing xy([x, y]);
			return yx(x[1], x[0]);
		}
		return yx(y, x);  // When doing xy(x, y);
	};
	//Now we can add a few stars and even a navigation line with [x, y] coordinates! (Shown down the page a bit)

	//Then we can just add a L.ImageOverlay with the starmap image and its approximate bounds:
	var bounds = [xy(0,0), xy(<%= @image.width %>,<%= @image.height %>)];
	//var image = L.imageOverlay('/images/demo-lease-plan.png', bounds).addTo(map);
	var image = L.imageOverlay('<%= @image.image_url %>', bounds).addTo(map);

	//map.setView(xy(120, 70), 1);
    map.fitBounds(bounds);
    
    //Let’s define our own icon class containing the shared options, 
    //inheriting from L.Icon! It’s really easy in Leaflet:
    var mapIcon = L.Icon.extend({
			options: {
				shadowUrl: '/images/clear-shadow.png',
				iconSize:     [30, 45], // size of the icon
                shadowSize:   [41, 41], // size of the shadow
                iconAnchor:   [15, 43], // point of the icon which will correspond to marker's location
                shadowAnchor: [12, 38],  // the same for the shadow
                popupAnchor:  [-3, -76] // point from which the popup should open relative to the iconAnchor
			}
		});

    //Now we can create all three of our leaf icons from this class and use them:
    var greenIcon = new mapIcon({iconUrl: '/images/green-marker.png'}),
    redIcon = new mapIcon({iconUrl: '/images/red-marker.png'}),
    orangeIcon = new mapIcon({iconUrl: '/images/orange-marker.png'}),
    blueIcon = new mapIcon({iconUrl: '/images/blue-marker.png'}),
    lblueIcon = new mapIcon({iconUrl: '/images/lblue-marker.png'}),
    blackIcon = new mapIcon({iconUrl: '/images/black-marker.png'}),
    fadedIcon = new mapIcon({iconUrl: '/images/faded-marker.png'}),
    yellowIcon = new mapIcon({iconUrl: '/images/yellow-marker.png'});
    
    <% @areas.each do |area| %>
        var <%= 's' + area.name.gsub(/\W\s?/, "") %> = <%= area.coords.html_safe %>;
        
        L.geoJson(<%= 's' + area.name.gsub(/\W\s?/, "") %>, {
        pointToLayer: function (feature, latlng) {
        return L.marker(latlng, {icon: fadedIcon});
        }}).addTo(map).setStyle({fillColor: '#dddd00', color: '#dddd00', weight: 1});

    <% end %>


    var popup = L.popup();


	var <%= 's' + @area.name.gsub(/\W\s?/, "") %> = <%= @area.coords.html_safe %>;

	//L.geoJson(<%#= 's' + @area.name.gsub(/\W\s?/, "") %>).addTo(map);
	//this was absurbed into the next variable

	// Initialise the FeatureGroup to store editable layers
	var drawnItems = L.geoJson(<%= 's' + @area.name.gsub(/\W\s?/, "") %>);
	map.addLayer(drawnItems);
	
	drawnItems.setStyle({<% if @area.status == 'Leased' %>fillColor: '#00dd00', color: '#00dd00', weight: 1<% else %>fillColor: '#dd0000', color: '#dd0000', weight: 1<% end %>});

	// Initialise and alter the draw control and pass it the FeatureGroup of editable layers
	var drawControl = new L.Control.Draw({
		draw: {
			//These options make up the root object that is used when initialising the Leaflet.draw control.
			position: 'topleft',
			polygon: false,
			polyline: false,
			rectangle: false,
			circle: false,
			marker: false
		},
		edit: {
			featureGroup: drawnItems
		}
	});
	map.addControl(drawControl);

	

	//draw:created - Triggered when a new vector or marker has been created.
	map.on('draw:edited', function (e) {
		var layers = e.layers;
		
    	layers.eachLayer(function (layer) {
	        //do whatever you want, most likely save back to db
	      		//var type = e.layerType,
				//layer = e.layer;
			
			var shape = layer.toGeoJSON()
	  		var shape_for_db = JSON.stringify(shape);
	
			document.getElementById('area_coords').value = shape_for_db;
	    });
	});
</script>

<hr style="clear:both;">

<%= render :partial => 'form' %>

app/views/areas/index.html.erb
<%- model_class = Area -%>

<h1>Because of the changes I made - this is no longer functioning properly. You want to be here: <%= link_to "Maps First Try", maps_path  %></h1>

<hr>

<h3>Here the map exists - The map is added one time manually.</h3>
<p>I can currently get all of the markers to show on the index page, and the individual marker to show on the show page.</p>

<div id='map' style="height:500px;"></div>


<script>
	//A Leaflet map has one CRS (and one CRS only), that can be changed when creating the map. 
	//For our game map we’ll use CRS.Simple, which represents a square grid:
	//In a CRS.Simple, one horizontal map unit is mapped to one horizontal pixel, 
	//and idem with vertical. This means that the whole map is about 1000x1000 pixels 
	//big and won’t fit in our HTML container. Luckily, we can set minZoom to values 
	//lower than zero:

	var map = L.map('map', {
		crs: L.CRS.Simple,
		minZoom: -3
	});

	//If working with [y, x] coordinates with something named L.LatLng doesn’t make much sense to you, 
	//you can easily create wrappers for them:
	var yx = L.latLng;

	var xy = function(x, y) {
		if (L.Util.isArray(x)) {    // When doing xy([x, y]);
			return yx(x[1], x[0]);
		}
		return yx(y, x);  // When doing xy(x, y);
	};
	//Now we can add a few stars and even a navigation line with [x, y] coordinates! (Shown down the page a bit)

	//Then we can just add a L.ImageOverlay with the starmap image and its approximate bounds:
	//In this case, the map covers more than 1000x1000 units, but the image is 2315x2315 pixels big
	//Different cases will call for one pixel = one map unit, or 64 pixels = one map unit, or anything. 
	//Think in map units in a grid, and then add your layers (L.ImageOverlays, L.Markers and so on) accordingly.
	//var bounds = [xy(-25, -26.5), xy(1023, 1021.5)];
	//var bounds = [[0,0], [753,1000]];
	var bounds = [xy(0,0), xy(1000,753)];
	var image = L.imageOverlay('/images/demo-lease-plan.png', bounds).addTo(map);

	//add some markers
	//var suite401      = yx(604, 107);
	//var suiteJ1      = yx(568, 275);
	//var suiteJ2      = yx(560, 579);
	//var sol      = xy(175.2, 145.0);
	//var mizar    = xy( 41.6, 130.1);
	//var kruegerZ = xy( 13.4,  56.5);
	//var deneb    = xy(218.7,   8.3);
	
	//You’ll notice that Sol is at coordinates [145,175] instead of [175,145], 
	//and the same happens with the map center. Coordinates in CRS.Simple take the form of [y, x] instead of [x, y], 
	//in the same way Leaflet uses [lat, lng] instead of [lng, lat].
	
	//(In technical terms, Leaflet prefers to use [northing, easting] over [easting, northing] - 
	//the first coordinate in a coordinate pair points “north” and the second points “east”)

	//L.marker(suite401).addTo(map).bindPopup('Suite 401');
	//L.marker(suiteJ1).addTo(map).bindPopup('Suite J-1');
	//L.marker(suiteJ2).addTo(map).bindPopup('Suite J-2');
	//L.marker(     sol).addTo(map).bindPopup(      'Sol');
	//L.marker(   mizar).addTo(map).bindPopup(    'Mizar');
	//L.marker(kruegerZ).addTo(map).bindPopup('Krueger-Z');
	//L.marker(   deneb).addTo(map).bindPopup(    'Deneb');

	//var travel = L.polyline([sol, deneb]).addTo(map);
	
  

	//map.setView(xy(120, 70), 1);
    map.fitBounds(bounds);

	//var marker = L.marker([598, 117]).addTo(mymap);
	
	//marker.bindPopup("<b>Hello world!</b><br>I am a popup.").openPopup();

    var popup = L.popup();
    
    function onMapClick(e) {
        popup
            .setLatLng(e.latlng)
            .setContent("You clicked the map at " + e.latlng.toString())
            .openOn(map);
    }
    
    map.on('click', onMapClick);
</script>

<script>
<% @areas.each do |area| %>
var <%= area.name %>      = yx(<%= area.coords %>);
L.marker(<%= area.name %>).addTo(map).bindPopup('<h3><%= area.name %> - <%= area.status %></h3><p><%= area.info %></p>');
<% end %>
</script>

<br style="clear:both;">

<p style="">Here I can add new areas. It asks for a name, info, status and coords. 
Overall this method would allow you to add one image map and many areas. 
It is a first step but will not be enough...</p>


<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:map_id) %></th>
      <th><%= model_class.human_attribute_name(:info) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:coords) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= link_to area.id, area_path(area) %></td>
        <td><%= link_to area.name, area_path(area) %></td>
        <td><%= area.map_id %></td>
        <td><%= area.info %></td>
        <td><%= area.status %></td>
        <td><%= area.coords %></td>
        <td><%=l area.created_at %></td>
        <td>
          <%= link_to t('.view', :default => t("helpers.links.view")),
                      area_path(area), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_area_path(area), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      area_path(area),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_area_path,
            :class => 'btn btn-primary' %>

<br><br><br>

app/views/areas/new.html.erb
<%- model_class = Area -%>



<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>

<p>
	*Adding a New Area is simple. Click within the bar on the left and choose the shape 
	you would like to draw. (Polygon, Rectangle or Marker!)
</p>

<div id='map' style="height:500px;"></div>


<script>
	//A Leaflet map has one CRS (and one CRS only)
	var map = L.map('map', {
		crs: L.CRS.Simple, 
		minZoom: -3
	});

	//If working with [y, x] coordinates with something named L.LatLng doesn’t make much sense to you, 
	//you can easily create wrappers for them:
	var yx = L.latLng;

	var xy = function(x, y) {
		if (L.Util.isArray(x)) {    // When doing xy([x, y]);
			return yx(x[1], x[0]);
		}
		return yx(y, x);  // When doing xy(x, y);
	};

	//add a L.ImageOverlay with the map image and its approximate bounds:
	//Think in map units in a grid, and then add your layers (L.ImageOverlays, L.Markers and so on) accordingly.
	var bounds = [xy(0,0), xy(<%= @image.width %>,<%= @image.height %>)];
	
	var image = L.imageOverlay('<%= @image.image_url %>', bounds).addTo(map);

	//add some markers
	//var suite401      = yx(604, 107);

	//L.marker(suite401).addTo(map).bindPopup('Suite 401');

	//map.setView(xy(120, 70), 1);
    map.fitBounds(bounds);
    
    //Let’s define our own icon class containing the shared options, 
    //inheriting from L.Icon! It’s really easy in Leaflet:
    var mapIcon = L.Icon.extend({
			options: {
				shadowUrl: '/images/clear-shadow.png',
				iconSize:     [30, 45], // size of the icon
                shadowSize:   [41, 41], // size of the shadow
                iconAnchor:   [15, 43], // point of the icon which will correspond to marker's location
                shadowAnchor: [12, 38],  // the same for the shadow
                popupAnchor:  [-3, -76] // point from which the popup should open relative to the iconAnchor
			}
		});


    //Now we can create all three of our leaf icons from this class and use them:
    var greenIcon = new mapIcon({iconUrl: '/images/green-marker.png'}),
    redIcon = new mapIcon({iconUrl: '/images/red-marker.png'}),
    orangeIcon = new mapIcon({iconUrl: '/images/orange-marker.png'}),
    blueIcon = new mapIcon({iconUrl: '/images/blue-marker.png'}),
    lblueIcon = new mapIcon({iconUrl: '/images/lblue-marker.png'}),
    blackIcon = new mapIcon({iconUrl: '/images/black-marker.png'}),
    fadedIcon = new mapIcon({iconUrl: '/images/faded-marker.png'}),
    yellowIcon = new mapIcon({iconUrl: '/images/yellow-marker.png'});    
    

    <% @areas.each do |area| %>
        var <%= 's' + area.name.gsub(/\W\s?/, "") %> = <%= area.coords.html_safe %>;
        
        L.geoJson(<%= 's' + area.name.gsub(/\W\s?/, "") %>, {
        pointToLayer: function (feature, latlng) {
        return L.marker(latlng, {icon: fadedIcon});
        }}).addTo(map).setStyle({fillColor: '#fff200', color: '#fff200', weight: 1});
    <% end %>
</script>

<script>
	// Initialise the FeatureGroup to store editable layers
	var drawnItems = new L.FeatureGroup();
	map.addLayer(drawnItems);


	// Initialise and alter the draw control and pass it the FeatureGroup of editable layers
	var drawControl = new L.Control.Draw({
		draw: {
			//These options make up the root object that is used when initialising the Leaflet.draw control.
			position: 'topleft',
			polygon: {
				title: 'Draw a sexy polygon!',
				allowIntersection: false,
				drawError: {
					color: '#00dd00',
					timeout: 1000
				},
				shapeOptions: {
					color: '#00dd00',
				weight: 1
				},
				showArea: true
			},
			polyline:  false,
			rectangle:  {
				shapeOptions: {
					color: '#00dd00',
				weight: 1
				}
			},
			circle: false
        },
		edit: {
			featureGroup: drawnItems
		}
	});
	map.addControl(drawControl);
	
	
	//draw:created - Triggered when a new vector or marker has been created.
	map.on('draw:created', function (e) {
		var type = e.layerType,
			layer = e.layer;
		
		var shape = layer.toGeoJSON()
  		var shape_for_db = JSON.stringify(shape);

		drawnItems.addLayer(layer);
		//trying some things here


		
		//alert(shape_for_db);
		document.getElementById('area_coords').value = shape_for_db;
	});
</script>

<hr style="clear:both;">



<%= render :partial => 'newform' %>

app/views/areas/show.html.erb
<%- model_class = Area -%>



<div id='map' style="height:500px;"></div>


<script>
	//A Leaflet map has one CRS (and one CRS only), that can be changed when creating the map. 
	//In a CRS.Simple, one horizontal map unit is mapped to one horizontal pixel, 

	var map = L.map('map', {
		crs: L.CRS.Simple,
		minZoom: -3
	});

	//If working with [y, x] coordinates with something named L.LatLng doesn’t make much sense to you, 
	//you can easily create wrappers for them:
	var yx = L.latLng;

	var xy = function(x, y) {
		if (L.Util.isArray(x)) {    // When doing xy([x, y]);
			return yx(x[1], x[0]);
		}
		return yx(y, x);  // When doing xy(x, y);
	};
	//Now we can add a few stars and even a navigation line with [x, y] coordinates! (Shown down the page a bit)

	//Then we can just add a L.ImageOverlay with the starmap image and its approximate bounds:
	var bounds = [xy(0,0), xy(<%= @image.width %>,<%= @image.height %>)];
	//var image = L.imageOverlay('/images/demo-lease-plan.png', bounds).addTo(map);
	var image = L.imageOverlay('<%= @image.image_url %>', bounds).addTo(map);

	//map.setView(xy(120, 70), 1);
    map.fitBounds(bounds);

    var popup = L.popup();
  
	var geojsonFeature = <%= @area.coords.html_safe %>;
	
	L.geoJson(geojsonFeature).addTo(map).bindPopup('<h3><%= @area.name %></h3><p><%= @area.info %></p>').setStyle(<% if @area.status == 'Leased' %>{fillColor: '#00dd00', color: '#00dd00', weight: 1}<% else %>{fillColor: '#dd0000', color: '#dd0000', weight: 1}<% end %>);
</script>



<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @area.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:info) %>:</strong></dt>
  <dd><%= @area.info %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @area.status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:coords) %>:</strong></dt>
  <dd><%= @area.coords %></dd>
</dl>


<hr style="clear:both;">
	<div style="width:100%;text-align:center;">
		<%= link_to '<= Back to Map',
		              map_path(@map), :class => 'btn btn-default'  %>
		<%= link_to 'Edit the Area =>',
		              edit_area_path(@area), :class => 'btn btn-primary' %>
		<%= link_to 'Delete the Area x',
		              area_path(@area),
		              :method => 'delete',
		              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
		              :class => 'btn btn-danger' %>
	</div>
<hr style="clear:both;">

<br><br>